# A sample Gemfile
source "https://rubygems.org"

gem 'wdm', '>= 0.1.0' if RbConfig::CONFIG['target_os'] =~ /mswin|mingw|cygwin/i
gem 'breakpoint', '>= 2.5.0'
gem 'susy', '>= 2.1.3'
gem 'compass', '>= 1.0.1'
gem 'sass', '>= 3.4.2'
gem 'sass-globbing', '>= 1.1.1'
