<?php
/**
* Do not edit this file. Edit the config files found in the wp-config/ dir instead.
* This file is required in the root directory so WordPress can find it.
* WP is hardcoded to look in its own directory or one directory up for wp-config.php.
*/






/** Enable W3 Total Cache */
define('WP_CACHE', true); // Added by W3 Total Cache


/** Enable W3 Total Cache Edge Mode */
define('W3TC_EDGE_MODE', false); // Added by W3 Total Cache


/* Init WP */
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/wp-config/application.php');
require_once(ABSPATH . 'wp-settings.php');